language: go

go:
    - "1.18"
    - "1.19"
    - "1.20"

script:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
    - go get ./...
    - go test ./...
    - go test -v -covermode=count -coverprofile=coverage.out
    - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
